version: 2

models:
- name: my_first_dbt_model
  description: "A starter dbt model"
  columns:
  - name: INVOICENO
    description: "The primary key for this table"
  - name: StockCode
    description: "The primary key for this table"
  - name: Description
    description: "The primary key for this table"
  - name: Quantity
    description: "The primary key for this table"
  - name: InvoiceDate
    description: "The primary key for this table"
  - name: UnitPrice
    description: "The primary key for this table"
  - name: CustomerID
    description: "The primary key for this table"
  - name: Country
    description: "The primary key for this table"

- name: my_second_dbt_model
  description: "A starter dbt model"
  columns:
  - name: id
    description: "The primary key for this table"
    data_tests:
    - unique
    - not_null
